/**
 * Syscoin API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AssetNewRequest { 
    /**
     * name, 20 characters max.
     */
    symbol?: string;
    /**
     * An alias you own.
     */
    alias?: string;
    /**
     * Public data, 256 characters max.
     */
    publicvalue?: string;
    /**
     * Category, 256 characters max. Defaults to assets.
     */
    category?: string;
    /**
     * Precision of balances. Must be between 0 and 8. The lower it is the higher possible max_supply is available since the supply is represented as a 64 bit integer. With a precision of 8 the max supply is 10 billion.
     */
    precision?: number;
    /**
     * Initial supply of asset. Can mint more supply up to total_supply amount or if total_supply is -1 then minting is uncapped.
     */
    supply?: number;
    /**
     * Maximum supply of this asset. Set to -1 for uncapped.
     */
    max_supply?: number;
    /**
     * If this asset uses an input for every token, useful if you need to keep track of a token regardless of ownership.
     */
    use_inputranges?: boolean;
    /**
     * The annual interest rate if any. Money supply is still capped to total supply. Should be between 0 and 1 and represents a percentage divided by 100.
     */
    interest_rate?: number;
    /**
     * Ability to adjust interest rate through assetupdate in the future.
     */
    can_adjust_interest_rate?: boolean;
    /**
     * Witness alias name that will sign for web-of-trust notarization of this transaction.
     */
    witness?: string;
}
